ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - host: msa-services.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

service:
  type: ClusterIP
  port: 8000

api_gateway:
  nameOverride: api-gateway

  image: 
    repository: api-gateway
    tag: latest
    pullPolicy: IfNotPresent

  fullname: "api_gateway"

  livenessProbe:
    httpGet:
      path: /health
      port: 8000
  readinessProbe:
    httpGet:
      path: /health
      port: 8000

keycloak:
  fullnameOverride: keycloak
  auth:
    adminUser: admin
    adminPassword: adminpassword

  replicaCount: 1

  service:
    type: ClusterIP
    port: 8081

  ingress:
    enabled: false

  extraEnv:
    - name: KEYCLOAK_FRONTEND_URL
      value: "http://keycloak:8081"

  postgresql:
    fullnameOverride: keycloak-postgresql
    enabled: true
    auth:
      postgresPassword: postgrespassword
      database: keycloak
      username: keycloak
      password: keycloakpassword
