auth:
  adminUser: admin
  adminPassword: adminpassword

replicaCount: 1

service:
  type: LoadBalancer
  port: 80

ingress:
  enabled: true
  ingressClassName: "nginx"
  hostname: keycloak.local
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m

postgresql:
  enabled: true
  auth:
    postgresPassword: postgrespassword
    database: keycloak
    username: keycloak
    password: keycloakpassword
