# For default values.yaml refer to https://github.com/helm/helm/blob/main/pkg/chartutil/create.go

replicaCount: 1

image:
  repository: api-gateway
  pullPolicy: IfNotPresent
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: 100m
  hosts:
    - host: tms-services.local
      paths:
        - path: /
          pathType: Prefix
  tls: []

resources: {}

livenessProbe:
  httpGet:
    path: /health
    port: 8000
readinessProbe:
  httpGet:
    path: /health
    port: 8000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

keycloak:
  auth:
    adminUser: admin
    adminPassword: adminpassword

  replicaCount: 1

  service:
    type: LoadBalancer
    port: 80

  ingress:
    enabled: true
    ingressClassName: "nginx"
    hostname: keycloak.local
    annotations:
      nginx.ingress.kubernetes.io/proxy-body-size: 100m

  postgresql:
    enabled: true
    auth:
      postgresPassword: postgrespassword
      database: keycloak
      username: keycloak
      password: keycloakpassword
