apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.api_gateway.nameOverride | default (include "msa-services.fullname" .) }}
  labels:
    {{- include "msa-services.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "msa-services.selectorLabels" . | nindent 4 }}
